openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Cars API'
  description: This is a simple API

paths:
  /cars:
    get:
      summary: searches cars
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
  /cars/{carId}:
    get:
        summary: searches cars
        parameters:
          - in: path
            name: carId
            description: pass an optional search string
            required: true
            schema:
              type: string
        responses:
          '200':
            description: search results matching criteria
